export enum EnvironmentEnum {
  SPOTIFY_CLIENT_ID = 'SPOTIFY_CLIENT_ID',
  SPOTIFY_CLIENT_SECRET = 'SPOTIFY_CLIENT_SECRET',
  DB_PATH = 'DB_PATH',
  DOWNLOADS_PATH = 'DOWNLOADS_PATH',
  FORMAT = 'FORMAT',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST',
  M3U_GENERATION_ENABLED = 'M3U_GENERATION_ENABLED',
}
