import * as fs from "fs";
import * as http from "http";
import * as https from "https";
import { resolve } from "path";
import { app } from "./app";
import { container } from "./container";
import { startScheduledJobs } from "./infrastructure/jobs";
import "./infrastructure/setup/env";
import { getEnv, validateEnvironment } from "./infrastructure/setup/environment";
import { initializeQueues } from "./infrastructure/setup/queues";

// Validate environment variables first
validateEnvironment();

const env = getEnv();
const PORT = 3000;

async function bootstrap() {
  console.log("🚀 Starting SpotiArr Backend...\n");

  // Create downloads directory if it doesn't exist
  const downloadsPath = resolve(__dirname, env.DOWNLOADS_PATH);
  if (!fs.existsSync(downloadsPath)) {
    fs.mkdirSync(downloadsPath, { recursive: true });
    console.log(`✅ Created downloads directory: ${downloadsPath}`);
  }

  // Initialize BullMQ queues
  initializeQueues();

  // Initialize workers
  await import("./infrastructure/workers/track-download.worker");
  await import("./infrastructure/workers/track-search.worker");

  // Check for stuck tracks and rescue them
  await container.rescueStuckTracksUseCase.execute();

  // Create server (HTTPS in production if certs exist, HTTP otherwise)
  const server = createServer();

  // Start scheduled jobs
  startScheduledJobs();

  // Start server
  server.listen(PORT, "0.0.0.0", () => {
    const isHttps = server instanceof https.Server;
    const protocol = isHttps ? "https" : "http";
    const protocolLabel = isHttps ? "🔒 HTTPS" : "🔓 HTTP";

    console.log(`\n✅ SpotiArr is running!`);
    console.log(`-------------------------------------------`);
    console.log(`🌍 Web UI:   ${protocol}://localhost:${PORT}`);
    console.log(`📡 API URL:  ${protocol}://localhost:${PORT}/api`);
    console.log(`🛡️  Protocol: ${protocolLabel}`);
    console.log(`-------------------------------------------`);

    if (env.NODE_ENV === "development") {
      console.log(`💻 Dev Frontend: http://localhost:5173`);
    } else if (isHttps) {
      console.log(
        `⚠️  Note: You might need to accept the self-signed certificate warning in your browser.`,
      );
    }
  });
}

function createServer(): http.Server | https.Server {
  const certPath = resolve(__dirname, "../../../config/server.cert");
  const keyPath = resolve(__dirname, "../../../config/server.key");

  // In production, try to use HTTPS if certificates exist
  if (env.NODE_ENV === "production" && fs.existsSync(certPath) && fs.existsSync(keyPath)) {
    try {
      const options = {
        key: fs.readFileSync(keyPath),
        cert: fs.readFileSync(certPath),
      };
      console.log("🔒 SSL Certificates found. Starting HTTPS server.");
      return https.createServer(options, app);
    } catch (error) {
      console.error("⚠️ Failed to load SSL certificates, falling back to HTTP:", error);
    }
  }

  // Development or no certificates available
  if (env.NODE_ENV === "production") {
    console.log("⚠️ No SSL certificates found at config/server.{cert,key}. Starting HTTP server.");
    console.log(
      "💡 For HTTPS in production, certificates will be auto-generated by Docker entrypoint.",
    );
  }

  return http.createServer(app);
}

bootstrap().catch((error) => {
  console.error("❌ Failed to start server:", error);
  process.exit(1);
});
