packages:
  - "apps/*"
  - "packages/*"
shamefullyHoist: true
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  ytdlp-nodejs: true
