import { APP_LOCALES, SettingMetadata } from "@spotiarr/shared";

export const SETTINGS_METADATA: Record<string, SettingMetadata> = {
  UI_LANGUAGE: {
    key: "UI_LANGUAGE",
    defaultValue: "en",
    type: "string",
    component: "select",
    section: "General",
    options: [...APP_LOCALES],
    label: "Interface Language",
    description: "Select your preferred language for the interface.",
  },
  SPOTIFY_MARKET: {
    key: "SPOTIFY_MARKET",
    defaultValue: "ES",
    type: "string",
    component: "select",
    section: "Spotify",
    options: [
      "ES",
      "US",
      "GB",
      "FR",
      "DE",
      "IT",
      "PT",
      "MX",
      "BR",
      "AR",
      "NL",
      "SE",
      "NO",
      "DK",
      "FI",
    ],
    label: "Spotify Market/Region",
    description:
      "2-letter ISO country code that affects content availability and regional restrictions. Change this to match your location for better results.",
  },
  AUTO_SUBSCRIBE_NEW_PLAYLISTS: {
    key: "AUTO_SUBSCRIBE_NEW_PLAYLISTS",
    defaultValue: "false",
    type: "boolean",
    component: "toggle",
    section: "Playlists",
    label: "Automatically subscribe to new playlists",
    description:
      "When enabled, new playlists are automatically subscribed. If disabled, you'll need to manually subscribe to them.",
  },
  PLAYLIST_CHECK_INTERVAL_MINUTES: {
    key: "PLAYLIST_CHECK_INTERVAL_MINUTES",
    defaultValue: "60",
    type: "number",
    component: "input",
    section: "Playlists",
    min: 30,
    max: 1440,
    label: "Playlist check interval (minutes)",
    description:
      "How often SpotiArr should re-check subscribed playlists on Spotify for new tracks. Lower values increase API usage.",
  },
  M3U_GENERATION_ENABLED: {
    key: "M3U_GENERATION_ENABLED",
    defaultValue: "true",
    type: "boolean",
    component: "toggle",
    section: "Playlists",
    label: "Automatically generate M3U playlists",
    description: "When enabled, an M3U file will be created/updated for each completed playlist.",
  },
  RELEASES_LOOKBACK_DAYS: {
    key: "RELEASES_LOOKBACK_DAYS",
    defaultValue: "14",
    type: "number",
    component: "input",
    section: "Releases",
    min: 7,
    max: 90,
    label: "New releases lookback period (days)",
    description: "How far back to look for new releases.",
  },
  FOLLOWED_ARTISTS_MAX: {
    key: "FOLLOWED_ARTISTS_MAX",
    defaultValue: "200",
    type: "number",
    component: "input",
    section: "Releases",
    min: 20,
    max: 300,
    label: "Maximum followed artists",
    description:
      "Maximum number of followed artists to consider across releases and artists views. Higher values may slow down the releases feed and increase API usage.",
  },
  RELEASES_CACHE_MINUTES: {
    key: "RELEASES_CACHE_MINUTES",
    defaultValue: "15",
    type: "number",
    component: "input",
    section: "Releases",
    min: 10,
    max: 120,
    label: "Cache duration (minutes)",
    description:
      "How long to cache releases data before refreshing from Spotify. Lower values increase API usage.",
  },
  FORMAT: {
    key: "FORMAT",
    defaultValue: "mp3",
    type: "string",
    component: "select",
    section: "Downloads",
    label: "Audio format",
    description: "The audio format for downloaded tracks.",
  },
  YT_AUDIO_QUALITY: {
    key: "YT_AUDIO_QUALITY",
    defaultValue: "best",
    type: "string",
    component: "select",
    section: "Downloads",
    options: ["best", "good", "acceptable"],
    label: "YouTube audio quality",
    description:
      "Audio quality preference for YouTube downloads. 'best' for highest quality, 'good' for balanced, 'acceptable' for faster downloads.",
  },
  YT_COOKIES: {
    key: "YT_COOKIES",
    defaultValue: "",
    type: "string",
    component: "input",
    section: "Downloads",
    label: "YouTube cookies browser (optional)",
    description:
      "Browser to extract cookies from for age-restricted content (e.g., 'chrome', 'firefox', 'edge'). Leave empty if not needed.",
  },
  YT_SEARCH_CONCURRENCY: {
    key: "YT_SEARCH_CONCURRENCY",
    defaultValue: "3",
    type: "number",
    component: "input",
    section: "Downloads",
    min: 1,
    max: 5,
    label: "YouTube search concurrency",
    description:
      "Number of simultaneous YouTube searches. Higher values are faster but may trigger rate limits.",
  },
  YT_DOWNLOADS_PER_MINUTE: {
    key: "YT_DOWNLOADS_PER_MINUTE",
    defaultValue: "5",
    type: "number",
    component: "input",
    section: "Downloads",
    min: 3,
    max: 8,
    label: "YouTube downloads per minute",
    description:
      "Maximum number of downloads that can start per minute to avoid YouTube throttling.",
  },
  DOWNLOAD_MAX_RETRIES: {
    key: "DOWNLOAD_MAX_RETRIES",
    defaultValue: "3",
    type: "number",
    component: "input",
    section: "Downloads",
    min: 1,
    max: 10,
    label: "Maximum download retries",
    description: "How many times to retry a failed download before giving up.",
  },

  STUCK_TRACKS_CLEANUP_INTERVAL_MINUTES: {
    key: "STUCK_TRACKS_CLEANUP_INTERVAL_MINUTES",
    defaultValue: "5",
    type: "number",
    component: "input",
    section: "Maintenance",
    min: 5,
    max: 60,
    label: "Stuck tracks cleanup interval (minutes)",
    description: "How often to check for and clean up stuck tracks.",
  },
  STUCK_TRACKS_TIMEOUT_MINUTES: {
    key: "STUCK_TRACKS_TIMEOUT_MINUTES",
    defaultValue: "10",
    type: "number",
    component: "input",
    section: "Maintenance",
    min: 5,
    max: 120,
    label: "Stuck tracks timeout (minutes)",
    description: "How long before a track is considered stuck and eligible for cleanup.",
  },
};
