import { APP_LOCALES, SettingMetadata } from "@spotiarr/shared";

export const SETTINGS_METADATA: Record<string, SettingMetadata> = {
  UI_LANGUAGE: {
    key: "UI_LANGUAGE",
    defaultValue: "en",
    type: "string",
    component: "select",
    section: "General",
    options: [...APP_LOCALES],
    label: "Interface Language",
    description: "Select your preferred language for the interface.",
  },
  SPOTIFY_MARKET: {
    key: "SPOTIFY_MARKET",
    defaultValue: "US",
    type: "string",
    component: "select",
    section: "Spotify",
    options: [
      "ES",
      "US",
      "GB",
      "FR",
      "DE",
      "IT",
      "PT",
      "MX",
      "BR",
      "AR",
      "NL",
      "SE",
      "NO",
      "DK",
      "FI",
    ],
    label: "Spotify Market/Region",
    description:
      "2-letter ISO country code that affects content availability and regional restrictions. Change this to match your location for better results.",
  },
  AUTO_SUBSCRIBE_NEW_PLAYLISTS: {
    key: "AUTO_SUBSCRIBE_NEW_PLAYLISTS",
    defaultValue: "false",
    type: "boolean",
    component: "toggle",
    section: "Playlists",
    label: "Automatically subscribe to new playlists",
    description:
      "When enabled, new playlists are automatically subscribed. If disabled, you'll need to manually subscribe to them.",
  },
  PLAYLIST_CHECK_INTERVAL_MINUTES: {
    key: "PLAYLIST_CHECK_INTERVAL_MINUTES",
    defaultValue: "60",
    type: "number",
    component: "input",
    section: "Playlists",
    min: 60,
    max: 1440,
    label: "Playlist check interval (minutes)",
    description:
      "How often SpotiArr should re-check subscribed playlists on Spotify for new tracks. Lower values increase API usage.",
  },
  M3U_GENERATION_ENABLED: {
    key: "M3U_GENERATION_ENABLED",
    defaultValue: "true",
    type: "boolean",
    component: "toggle",
    section: "Playlists",
    label: "Automatically generate M3U playlists",
    description: "When enabled, an M3U file will be created/updated for each completed playlist.",
  },
  FORMAT: {
    key: "FORMAT",
    defaultValue: "mp3",
    type: "string",
    component: "select",
    section: "Downloads",
    label: "Audio format",
    description: "The audio format for downloaded tracks.",
  },
  YT_AUDIO_QUALITY: {
    key: "YT_AUDIO_QUALITY",
    defaultValue: "best",
    type: "string",
    component: "select",
    section: "Downloads",
    options: ["best", "good", "acceptable"],
    label: "YouTube audio quality",
    description:
      "Audio quality preference for YouTube downloads. 'best' for highest quality, 'good' for balanced, 'acceptable' for faster downloads.",
  },
  YT_COOKIES: {
    key: "YT_COOKIES",
    defaultValue: "",
    type: "string",
    component: "textarea",
    section: "Downloads",
    label: "YouTube Cookies",
    description:
      "Paste the content of your cookies.txt (Netscape format). It will be saved as a file.",
  },
  DOWNLOAD_MAX_RETRIES: {
    key: "DOWNLOAD_MAX_RETRIES",
    defaultValue: "3",
    type: "number",
    component: "input",
    section: "Downloads",
    min: 1,
    max: 5,
    label: "Maximum download retries",
    description: "How many times to retry a failed download before giving up.",
  },
};
