export const ApiRoutes = {
  BASE: "/api",
  EVENTS: "/events",
  PLAYLIST: "/playlist",
  TRACK: "/track",
  HISTORY: "/history",
  SETTINGS: "/settings",
  ARTIST: "/artist",
  FEED: "/feed",
  AUTH: "/auth",
  AUTH_UNLOCK: "/auth/unlock",
  AUTH_SESSION: "/auth/session",
  HEALTH: "/health",
  LIBRARY: "/library",
  SEARCH: "/search",
  EXTERNAL_URL: "/external-url",
  AI: "/ai",
} as const;
