export enum Path {
  HOME = "/",
  PLAYLIST_DETAIL = "/playlist/:id",
  PLAYLIST_PREVIEW = "/preview",
  HISTORY = "/history",
  DASHBOARD = "/dashboard",
  SETTINGS = "/settings",
  RELEASES = "/releases",
  ARTISTS = "/artists",
  ARTIST_DETAIL = "/artist/:id",
  LIBRARY_ARTIST = "/library/artist/:name",
  LIBRARY_ALBUM = "/library/artist/:name/album/:albumName",
  MY_PLAYLISTS = "/my-playlists",
  SEARCH = "/search",
  ALBUM_DETAIL = "/album/:artistId/:albumId",
  CHAT = "/chat",
}
