import { library } from "@fortawesome/fontawesome-svg-core";
import { faSpotify } from "@fortawesome/free-brands-svg-icons";
import {
  faBell as faBellRegular,
  faClock as faClockRegular,
} from "@fortawesome/free-regular-svg-icons";
import {
  faBars,
  faBell,
  faBroom,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleArrowDown,
  faCircleCheck,
  faCircleExclamation,
  faClockRotateLeft,
  faCompactDisc,
  faDownload,
  faHouse,
  faHourglassHalf,
  faLink,
  faMagnifyingGlass,
  faMugHot,
  faMusic,
  faRepeat,
  faRotate,
  faRotateRight,
  faSliders,
  faSpinner,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserGroup,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  // Solid
  faBars,
  faBell,
  faBroom,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleArrowDown,
  faCircleCheck,
  faCircleExclamation,
  faClockRotateLeft,
  faCompactDisc,
  faDownload,
  faHouse,
  faHourglassHalf,
  faLink,
  faMagnifyingGlass,
  faMugHot,
  faMusic,
  faRepeat,
  faRotate,
  faRotateRight,
  faSliders,
  faSpinner,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserGroup,
  faXmark,
  // Regular
  faBellRegular,
  faClockRegular,
  // Brands
  faSpotify,
);
